version: "3.5"

services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - .data/squid/archive/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squid-archive

  ingest:
    depends_on:
      - db
    restart: on-failure
    image: subsquid/substrate-ingest:0
    command: [
       "-e", "ws://bob:9944",
       "-c", "20", # allow up to 20 pending requests for the above endpoint (default is 5)

       # add another endpoint to increase archiving speed and reliability.
       # "-e", "wss://shibuya.public.blastapi.io",
       #  "--start-block", "1000000", # uncomment to specify a non-zero start block
       "--out", "postgres://postgres:postgres@db:5432/squid-archive"
    ]
    ports:
      - "9090:9090" # prometheus port

  archive:
    depends_on:
      - db
    image: subsquid/substrate-gateway:1.2.0
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: [
       "--database-url", "postgres://postgres:postgres@db:5432/squid-archive",
       # "--evm-support" # uncomment for chains with Frontier EVM pallet
                         # (e.g. Moonbeam/Moonriver or Astar/Shiden)
    ]
    ports:
      - "8888:8000"

networks:
  default:
    name: local-testnet
