version: "3.5"

x-environment: &envs
  CHAIN: local
  PROCESSOR_NAME: squid-local
  DB_NAME: postgres
  DB_HOST: squid-db
  DB_PASS: postgres
  DB_PORT: 5432
  PROCESSOR_PROMETHEUS_PORT: 5000
  GQL_PORT: 5555
  ARCHIVE_ENDPOINT: http://host.docker.internal:8001/graphql
  WS_ENDPOINT: wss://edgeware.jelliedowl.net
  BALANCES_STORE: system
  SOURCE_CODE_ENABLED: "true"
  VERIFIER_ENDPOINT: http://host.docker.internal:3001

services:
  squid-db:
    image: postgres:15
    restart: on-failure
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squid-db
    ports:
      - "5432"


  processor:
    container_name: subsquid-processor
    image: ghcr.io/web3labs/squid-ink-epirus
    restart: on-failure
    environment: *envs
    command: sh -c "(npx sqd up && npx sqd migration:generate); sleep 5 && npm run processor:start"
    depends_on:
      - squid-db
    extra_hosts:
      - host.docker.internal:host-gateway

  query:
    container_name: query-node
    image: ghcr.io/web3labs/squid-ink-epirus
    restart: on-failure
    environment: *envs
    ports:
      - "5555"
    depends_on:
      - processor

networks:
  default:
    name: local-testnet
